apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
      - name: survey-container
        image: kshah1025/img:0.1
        ports:
        - containerPort: 80
